server: 
  port: 9001
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9001.com
    prefer-ip-address: true 
 
 
zuul:

  prefix: /lever
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: lever-microcloud
  company.name: lever
  build.artifactId: $project.artifactId$
  build.version: $project.version$

